Practice/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Practice.Models;
using Practice.ViewModels;

namespace Practice.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> userManager;

        public PostsController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        // GET: Posts
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var posts = await _context.Posts.ToListAsync();
            var users = await _context.Users.ToListAsync();
            if (users == null)
            {
                return NotFound();
            }
            var viewPosts = posts.Where(p => p.UserId != null).Select(p => new PostListViewModel(p, users.Where(u => u.Id != null).FirstOrDefault(u => u.Id == p.UserId).UserName)).ToList();
            if (viewPosts == null)
            {
                return NotFound();
            }
            return View(viewPosts);
        }
        [AllowAnonymous]
        public async Task<IActionResult> UserPosts(string id)
        {
            var posts = await _context.Posts.ToListAsync();
            var user = await userManager.FindByIdAsync(id);
            var viewPosts = posts.Where(p => p != null).Where(p => p.User != null).Where(p => p.User.Equals(user)).Select(p => new PostListViewModel(p, user.UserName)).ToList();
            return View("Index", viewPosts);
        }

        public async Task<IActionResult> MyPosts()
        {
            var posts = await _context.Posts.ToListAsync();
            var user = await userManager.GetUserAsync(User);
            var viewPosts = posts.Where(p => p != null).Where(p => p.User != null).Where(p => p.User.Equals(user)).Select(p => new MyPostViewModel(p)).ToList();
            return View("MyPosts", viewPosts);

        }

        // GET: Posts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.IdPost == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPost,Title,Slug,Content")] Post post)
        {
            if (ModelState.IsValid)
            {
                post.User = await userManager.GetUserAsync(User);
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MyPosts));
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            var currentUser = await userManager.GetUserAsync(User);
            if (!(post.UserId).Equals(currentUser.Id))
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPost,UserId,Title,Slug,Content")] Post post)
        {
            if (id != post.IdPost)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentUser = await userManager.GetUserAsync(User);
                    if (!(post.UserId).Equals(currentUser.Id))
                    {
                        return NotFound();
                    }
                    post.User = currentUser;
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.IdPost))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MyPosts));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.IdPost == id);
            if (post == null)
            {
                return NotFound();
            }
            var currentUser = await userManager.GetUserAsync(User);
            if (!(post.UserId).Equals(currentUser.Id))
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Posts'  is null.");
            }
            var post = await _context.Posts.FindAsync(id);

            if (post != null)
            {
                var currentUser = await userManager.GetUserAsync(User);
                if (!(post.UserId).Equals(currentUser.Id))
                {
                    return NotFound();
                }
                _context.Posts.Remove(post);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MyPosts));
        }

        private bool PostExists(int id)
        {
          return (_context.Posts?.Any(e => e.IdPost == id)).GetValueOrDefault();
        }
    }
}

Practice/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Practice.Models;
using Practice.ViewModels;

namespace Practice.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
        }

        public  IActionResult Index()
        {
            return _context.Users != null ?
                    View(_context.Users.ToList()) :
                    Problem("Entity set 'ApplicationDbContext.Posts'  is null.");
        }

        public IActionResult Details(string? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = _context.Users.FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(new UserDetailViewModel(user));
        }
    }
}

Practice/Views/Shared/_Layout.cshtml
@inject SignInManager<User> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practice.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practice</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (!signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Log In</a>
                            </li>
                        } else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Edit">Hi, @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="MyPosts">My Posts</a>
                            </li>
                            <li class="nav-item">
                                <form method="post">
                                    <button class="nav-link btn btn-link text-dark" type="submit" asp-area="" asp-controller="Account" asp-action="Logout">Log Out</button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Practice
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>